HOSTS:
  ossecserver:
    roles:
      - agent
    platform: ubuntu-1404-x86_64
    box: puppetlabs/ubuntu-14.04-64-nocm
    hypervisor: vagrant
    ip: 10.10.11.10
    vagrant_memsize: 2048
  ossecagent-win-29:
    roles:
      - agent
      - ossecwin29
      - default
    platform: windows-2012_r2-amd64
    box: opentable/win-2012-standard-amd64-nocm
    hypervisor: vagrant
    user: vagrant
    ip: 10.10.11.11
    vagrant_memsize: 2048
    is_cygwin: false
CONFIG:
  type: foss
  log_level: verbose
